server:
  port: 9090

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/image?serverTimezone=Asia/Shanghai
    username: root
    password: 12345678
  # 文件上传
  servlet:
    multipart:
      #       设置单个文件大小
      max-file-size: 100MB
      #       设置单次请求文件的总大小
      max-request-size: 5000MB

mybatis:
  mapper-locations: classpath:mapper/*.xml  #扫描所有mybatis的xml文件
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

files:
  upload:
    path: E:/Data/images/



# 服务模块
devtools:
  restart:
    # 热部署开关
    enabled: true
